[Logger]
; Debug Console
Console=1
PrintScriptNames=0
; Prints to debug.txt file in game directory.
WriteFile=1
ExitOnAssert=1
; Prints a line of text into Console/debug.txt every single time an asset is read by the game. (This can spam logs and make debug.txt file size large.)
AssetLoadPrint=0

[Debug]
; Changes the keybind for Lua Executor. refer to https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes for the key "value"s. (Clippy95)
ExecutorBind=45
AllowMultipleSR2Windows=1
TervelTextureCrashWorkaround_be_as_pe=1
; Patches in Juiced Patch custom updates to settings adding MSAA 8x Support and fixing up label names, required for Ultrawide support.
Hook_lua_load_dynamic_script_buffer=1
FixCrashes=2
DisableAssertsPopUp=0
; Replaces old in-game math functions with more optimized SSE2+ functions, provides a major FPS boost in certain areas of the game
; Also helps achieve better performance parity between AMD and Intel CPUs, as AMD CPUs previously had worse performance with the original functions compared to Intel CPUs. (Clippy95 & Tervel)
FastMath=1
; Implements a workaround to water volume causing tsunami like waves when flicking camera orientation around for a few seconds (only was possible with mouse) (Clippy95)
FixWaterVolumeCameraBug=1
; Prints mission and lua scripting printf calls to the debug console.
LUADebugPrintF=1
; Disables Controller Inputs Completely. If you aren't planning on using a controller and are experiencing load/new game crashes, use this with the option below.
DisableXInput=0
; Forces Vibration to be disabled. This will most likely fix the rare load/new game save crashes some users have.
ForceDisableVibration=0
FixGFL1_for_female_playas=1
ClippyTextureCrashExceptionHandle=1
; Uncaps the fps from sub-30 when alt-tabbed.
AltTabFPS=1
; UncapFPS quite literally Uncaps the Framerate past the 100 fps limit on the base game. !!!! THIS WILL ALSO INCREASE CPU USAGE !!!!
UncapFPS=0
; Fixes performance by waiting properly between main game thread and render thread.
; recommended to be used alongside sync_shadows_threads=1 (Clippy95)
FixPerformance=1
; This will hook sleep and divide sleep-time by half, NOT RECOMMENDED, no support will be provided for playing with this option toggled on!, EXPECT ISSUES!
SleepHook=0
; Raises fps cap in Legal/Loading screens to 60 from 30 to make those screens slightly faster.
; Also removes a sleep call during world/asset streaming, hopefully reducing stuttering and bringing parity with the X360 version.
FasterLoading=1
; Implements proper thread synchronization for shadow jobs, makes SleepHack 2 obsolete as threads are in sync properely now.
; Also heavily reduces CPU usage compared to this setting turned off + Sleephack 2. (Clippy95, Silent)
sync_shadows_threads=1
ShadowThreadCount=4
; Renders the loose files that load during the initial loading screen (Clippy95)
DisplayLooseFilesLoading=1
; [EXPERIMENTAL] Fixes stereo output in cutscenes, very experimental in its current state.
FixAudio=0
; Adds Custom Option Binds to the F Keys [F1-F9]
AddBindToggles=0
; Fixes Cutscene Object Syncage and Doors teleporting on high fps.
FixFrametime=1
; Shows Version Number on Main Menu and/or Pause Menu. (Tervel)
; 1 = on
; 0 = off
MenuVersionNumber=1
; Both of these patches will disable the fake distant models for either the peds or the vehicles. (Tervel)
DisableDistantPeds=0
; Both of these patches will disable the fake distant models for either the peds or the vehicles. (Tervel)
DisableDistantVehicles=0
unhook_after_patching_xtbl_read_and_parse_file=1
PopulateInGameOptions=1
ReadJuicedWarning=0
[Input]
EnableDynamicPrompts=2
; Fixes Y mouse sensitivity being tied to aspect ratio. (Clippy95)
FixVerticalMouseSensitivity=1
; Swaps xinput with SDL
SDL=1
KEY_inventory_up=W
KEY_inventory_down=S
KEY_inventory_left=A
KEY_inventory_right=D
; Allows extra binding for within the radial menu (food/drink menu) (Clippy95)
better_inventory_keyboard=1
HoldFineAim=0
ForceInputPrompt=0
ForcedControllerPrompts=0
MouseFOVScaling=0
[UGC]
CModLoader=1
[API]
JuicedAPI=1
[Modding]
addon_bitmaps=1
extra_hash_table_size=0
[Mempool]
permanent=12582912
Bitmap_Image_Names_hashtable=24000
Bitmap_Image_Names=73728
; Default 1114112
perm_mesh_cpu=2228224
; Default 102760448
audio_wavebank=102760448
; Default 17293312
animation=34586624
; Opens a popup when mempool alloc fails (Clippy95)
mempool_print_error=1
interface_gpu_multi=1.500000
[Misc]
DefaultToNativeRes=1
; Turning this option on makes it so saved games and settings load from "SR2 GAME DIRECTORY//userdata"
portable=0
; Discord Rich Presence
RichPresence=1
UpdateChecks=1
[Graphics]
FixUltrawideHUD=1
; Makes Brake lights visible when a running vehicle is at a full stop while the engine is running (Clippy95)
ProperBrakeLights=1
; Removes Pixelation/censor filter from the game. (Clippy95)
RemovePixelationShader=0
ShaderOverride=1
; Accurately replicates the XBOX 360 gamma visuals. (Tervel)
X360Gamma=1
; Applies a smooth filtering shader to shadows (Tervel)
ShadowFiltering=0
; Removes the Vignette screen effect (Creds to Clippy95 and Tervel)
RemoveVignette=0
; Disables an FXAA like effect that runs on the game
DisableScreenBlur=1
; Overhauls the lighting, keeping the SR2 feel while removing the orangey/yellow screen filter and sharpening up the look of everything.
; (MAY INTERFERE WITH GRAPHICS/TIME OF DAY MODS FOR SR2)
VanillaFXPlus=0
; Disables Distance Fog (Creds to Tervel)
DisableFog=0
; Uses a custom first person mode camera on-foot. 2 has viewmodel, 1 has no viewmodel.
FirstPersonCamera=0
; Makes idle animations snap to where the camera is pointing (like GTA3/VC)
ClassicGTAIdle=0
; 2 = Maps the resolution to your screens resolution
; 1 = Same as above but half res (Example: 1920x1080 > 1280x720 resolution scale.)
; 0 = Vanilla Resolution
; Increases resolution of Depth-of-field, skydive blur, reflections and bloom (Tervel)
UHQScreenEffects=1
; Removes Cutscene Black Bars (By Tervel)
RemoveBlackBars=0
; Disables the blue sky reflections in building windows (Tervel)
DisableSkyRefl=0
; Smoothens the Ambient occlusion, crushing the noisy output the base games AO has.
BetterAmbientOcclusion=1
; Fixes the glares not showing up when you drive up to a chunk as opposed to teleporting or loading into one (Tervel)
FixGlares=1
; Adds a PostFX filter to smooth out the fallback dithering with MSAA off/no alpha mask available, but blurs the screen slightly (Tervel)
DitherFiltering=1
; Sets the shadow map resolution to anything from the vanilla 960x960 up to 10x the vanilla resolution. (Tervel)
; Some recommened values: 2048, 4096, 8192
ShadowMapRes=960
; Ties player cursor in minimap and pause map to the actual player orientation rather than camera when using the "Minimap view: Rotational" setting (Clippy95)
mini_pause_map_PlayerRotation=1
; Applies XBOX 360 gamma on HUD elements. (Clippy95)
X360GammaUI=1
; Borderless windowed, this replaces Windowed mode in-game.
Borderless=1
; Safearea in ultrawide for elements defined in cvint.dat (clippy95)
SafeArea_X_UW=1.000000
; Proper letterboxing for different aspect ratios above widescreen while in cutscenes (clippy95)
SmartCutsceneBorders=1
DynamicRenderDistance=0
; Makes the minimap scaling more in line with GTA IV (Clippy95)
IVRadarScaling=0

[DLC]
; Requires DLC content to be installed otherwise does nothing
EnableDLC=1

[Multiplayer]
; stores MP player data such as cash and customization in alocalappdata/THQ/Saints Row 2/Juiced/mp/MPStorage.mpdt_pc file rather than Game/OpenSpy (clippy95)
StoreStorageLocally=1
; Fixes the multiple network adapter issue which makes it so you can't use online functionalities if you had more than 1 network adapter.
FixNetworkBinding=1
; Changes the lobby maps.
NewLobbyList=1
Lobby1=sr2_mp_lobby02
Lobby2=sr2_mp_lobby03
; Makes all clothing free in Multiplayer.
FreeMPClothing=0

[Gameplay]
; Allows for manual reloading of weapons while in vehicles. (Clippy95)
allow_reloading_in_cars=0
; Disables Aim Assist (Creds to Clippy95 and Tervel)
; 0 - Vanilla behaviour
; 1 - Disables for Mouse Only
; 2 - Disables entirely
DisableAimAssist=1
; Fixes Massive Deadzone issues while Spray Tagging Walls. (Creds to Clippy95)
TagHook=1
; Maps the turning speed in wardrobe/shop to your native mouse/controller analog input (Clippy95)
; 0 - Base Game behaviour
; 1 - Updated behaviour 
BetterPlayerWardrobeRotate=1
SwapScrollWheel=0
SR1VehicleCameraTransition=0
; Disables camera shake while sprinting (Clippy95)
DisableSprintCamShake=0
; Changes the auto center camera timer while in a vehicle (in milliseconds) (Clippy95)
; Remove ";" from below if you would like to use this feature.
; VehicleAutoCenterModifier=25
; Changes the camera turning speed back to the center.
vehicle_camera_follow_modifier=1.000000
; Disarms characters and the player everytime ragdoll is initiated.
AlwaysDisarmOnRagdoll=0
; Allows you to sprint while on fire, just like in SR1! (Clippy95)
SprintWhileOnFire=0
; Allows weapon switching when sprinting, etc (Clippy95)
AllowWeaponSwitchInAllCases=0
; Makes it so the cam doesnt chase the car when you do a powerslide/handbrake. (Creds to Clippy95)
BetterHandbrakeCam=0
; Fixes the drive-by camera by making it unlocked from the front forward axis of the car. (Makes it easier to aim) (Creds to Clippy95)
BetterDriveByCam=1
; Allows you to crouch while jogging (Clippy95)
AllowToggleCrouchWhileWalk=1
; Disables Camera locking when Mantling/Climbing over walls. (Clippy95)
DisableCameraLockForClimb=1
; Skips the open/kick animation for opening doors.
FastDoors=0
; Allows you to reload while sprinting (Tervel)
SR1Reloading=0
; Disables the forced player orientation change when attacking while next to an NPC - takedowns will not work with this option due to them heavily depending on a lock-on target. (Tervel)
NoMeleeLockOn=0
; Crouch camera acts the same regardless if you're armed or unarmed (Clippy95)
SR1CrouchCam=1
; Restores the quick switching technique from SR1 (Tervel)
SR1QuickSwitch=0
; Allows you to cancel taunt/compliment by simply pressing the taunt/compliment button again. (Tervel)
TauntCancelling=1
; Keeps your empty weapon equipped after you've run out of ammo for that weapon (Tervel)
UseWeaponAfterEmpty=1
; Stops some animation events from running, more notably the 180 turn anims that add extra movement delay. Feels like SR1 movement.
BetterMovementBehaviour=0
SR1MovingAttacks=0
; Removes xtbl's 100 mph hardcoded limit on vehicle speeds (ithinkimcats, Clippy95)
HigherMaxSpeed=0
VehicleAutoCenterModifer=0
; Increases the distance where vehicles fade if you are not looking at them
IncreaseVehicleFadeDistance=1
FixUltrawideFOV=1
; Field of View, affects cutscenes and gameplay.
FOVMultiplier=1.000000
; Increases character limit for Text Chat in Multiplayer (Creds to Tervel)
BetterChat=1
; Skips Startup Logos and Disclaimers (Creds to Tervel)
SkipIntros=0
; Disables Cheat Flagging (Creds to Clippy95)
DisableCheatFlag=0
; Automatically Loads your last saved game upon main menu boot up. (Creds to Tervel)
LoadLastSave=0
ForceMetricSystem=0
DisableTutorials=0
[Audio]
FixAudioDeviceAssign=1
; Fixes audio playback across the board, Replaces the ingame XAudio 2.2 to XAudio 2.3. (Creds to Scanti)
; Setting this to 1 enables it for Windows Systems, requires 2 for Linux/Wine and proper XACT install (use winetricks or protontricks)
UseFixedXAudio=1
; Toggles the games in-built 5.1 Surround Support. (Scanti)
51Surround=0
